language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  - provider: npm
    edge:
      branch: v1.8.47
    skip_cleanup: true
    email: $EMAIL
    api_key: $API_KEY
    on:
      branch: release
  - provider: pages
    edge:
      branch: v1.8.47
    fqdn: npmtestxxx.js.org
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep-history: true
    local_dir: docs
    on:
      branch: release