language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
install:
  - npm ci
script:
  - npm run build
jobs:
  include:
    - stage: release
      node_js: "lts/*"
      script:
        - npm shrinkwrap
      deploy:
        provider: npm
        email: $EMAIL
        api_key: $API_KEY
        on:
          branch: release
          tags: true
