language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run build
  - echo $GITHUB_PAGES_CNAME > docs/CNAME
deploy:
  # - provider: npm
  #   email: $EMAIL
  #   api_key: $API_KEY
  #   skip_cleanup: true
  #   on:
  #     branch: release
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: docs
  on:
    branch: release