language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  edge:
    branch: pages-ivar-set
  provider: pages
  fqdn: npmtestxxx.js.org
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: docs
  on:
    branch: release