language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

jobs:
  include:
    - stage: building
      script:
        - npm install
        - npm run build
    - stage: tests
      script: echo "tests stage"
    - stage: npm_release
      deploy:
        provider: npm
        email: $EMAIL
        api_key: $API_KEY
        on:
          branch: release
        skip_cleanup: true
    - stage: github_pages
      script: echo "github pages"