language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
cache:
  directories:
  - node_modules
script:
  - npm run build
jobs:
  include:
    - stage: release
      node_js: "8"
      deploy:
        provider: npm
        email: $EMAIL
        api_key: $API_KEY
        on:
          branch: release
          tags: true
